### ISSUE TITLE
wont start after upgrade

### ISSUE THREAD

**Issue by Craigzyc** [binhex/arch-sickrage#3] opened 2017-02-13 17:57 UTC
As of the newest upgrade release dated 2017.02.12-2-01 docker will not start this container.
No logs either, just exits

**Comment by binhex** [comment] 2017-02-13 20:23
ive just pulled this and ran it against my existing config files and the upgrade went smoothly with no issues on startup, so im confident the issue is not with the image. if your not seeing any logs then my guess would be a port conflict with an existing container, make sure you dont have anything else running on the same port on the host side, the output from the docker run command should give you a hint as to what is happening.

**Comment by Craigzyc** [comment] 2017-02-13 20:37
I can try that when I'm home but I did just try changing the port to another available port and it still failed.

**Comment by binhex** [comment] 2017-03-21 11:40
closing as there have been a lot of changes since this issue was opened, if your still having a problem then please open a new issue.

**Closed by binhex** 2017-03-21 11:40 UTC
